//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AED_Tecno_Compras.Base_de_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.ProductoEnFactura = new HashSet<ProductoEnFactura>();
        }
    
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string UrlFoto { get; set; }
        public float PrecioUnitario { get; set; }
        public int CantidadEnInventario { get; set; }
        public Nullable<float> Descuento { get; set; }
        public Nullable<System.DateTime> FechaInicioDescuento { get; set; }
        public Nullable<System.DateTime> FechaFinDescuento { get; set; }
        public int IdCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<ProductoEnFactura> ProductoEnFactura { get; set; }
    }
}
